const config = {
    ownerNumber: ['584265306799'],
    botName: '𝙴𝚂𝙲𝙰𝙽𝙾𝚁-𝙱𝙾𝚃',
    botOwner: '⌗𝐄𝐒𝐂𝐀𝐍𝛩𝐑',
    ownerLink: 'https://wa.me/message/GS4F67GW4JCBK1',
    channelLink: 'https://whatsapp.com/channel/0029VbBbvWcJ3jv1T55BmR0f',
    supportGroup: 'https://chat.whatsapp.com/KitwsW1PEl23WSwiooXMNh',
    botImage: 'https://i.postimg.cc/7LJ6rKH2/1cb4202c15867027d896dfd71a9eaeeb.jpg',
    installImage: 'https://i.postimg.cc/FzpRx2rC/Picsart-26-05-15-10-08-36-713.jpg',
    prefix: '.',
    pairingCode: 'ESCANOR1',
    sessionDir: './session',
    dbPath: './data/database.json',
    maxWarn: 3,
    antiLink: true,
    antiSpam: true,
    antiFlood: true,
    floodLimit: 5,
    floodTime: 5000,
    autoRead: false,
    autoTyping: true,
    prayerReminder: true,
    welcomeMsg: true,
    goodbye: true,
    ranks: [
        { level: 0,  name: 'جندي',       xp: 0 },
        { level: 1,  name: 'عريف',       xp: 100 },
        { level: 2,  name: 'رقيب',       xp: 300 },
        { level: 3,  name: 'رقيب أول',   xp: 600 },
        { level: 4,  name: 'مساعد',      xp: 1000 },
        { level: 5,  name: 'ملازم',      xp: 1500 },
        { level: 6,  name: 'ملازم أول',  xp: 2200 },
        { level: 7,  name: 'نقيب',       xp: 3000 },
        { level: 8,  name: 'رائد',       xp: 4000 },
        { level: 9,  name: 'مقدم',       xp: 5500 },
        { level: 10, name: 'عقيد',       xp: 7500 },
        { level: 11, name: 'عميد',       xp: 10000 },
        { level: 12, name: 'لواء',       xp: 13000 },
        { level: 13, name: 'فريق',       xp: 17000 },
        { level: 14, name: 'فريق أول',   xp: 22000 },
        { level: 15, name: 'مشير',       xp: 30000 },
        { level: 16, name: 'مساعد وزير', xp: 40000 },
        { level: 17, name: 'وزير',       xp: 55000 },
    ],
    sections: []
};

export default config;
